### ISSUE TITLE
How can I install this package

### ISSUE THREAD

**Issue by maxi1192** [armijnhemel/bat-extratools-java#1]
Like in the documentation of bat, these extratools are mandatory. But There is no .deb file like for bat-extratools and bat itself. That's why I need to build it from git repo, righ?
I tried two approaches:
1. running ant
-> compiles but when I want to install bat using dpkg it says:
`bat depends on bat-extratools-java (>= 26.0); 
however: Package bat-extratools-java is not installed.`

2. running debuild -i
-> also compiles but throws error in the end:
```
debsign: gpg error occurred!  Aborting....
debuild: fatal error at line 1283:
running debsign failed
```
and the error message installing bat using dpkg also occurs

What is the right way to install bat-extratools-java?

**Comment by armijnhemel** [comment]
On 12/06/2016 01:24 PM, maxi1192 wrote:
>
> Like in the documentation of bat, these extratools are mandatory. But
> There is no .deb file like for bat-extratools and bat itself. That's
> why I need to build it from git repo, righ?
>

No, I removed the dependency. It is no longer needed :-)

armijn


-- 
Armijn Hemel, MSc
Tjaldur Software Governance Solutions

**Comment by darcyfdu** [comment]
You said you had removed the dependency. But this is the info when i install from bat_27.0_all..deb 
darcy@darcy-pc:~$ sudo dpkg -i bat_27.0_all.deb 
Selecting previously unselected package bat.
(Reading database ... 164283 files and directories currently installed.)
Preparing to unpack bat_27.0_all.deb ...
Unpacking bat (27.0) ...
dpkg: dependency problems prevent configuration of bat:
 bat depends on bat-extratools-java (>= 26.0); however:
  Package bat-extratools-java is not installed.

dpkg: error processing package bat (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 bat
It require for bat-extratools-java,what should I do?

**Comment by armijnhemel** [comment]
The dependency has been gone, but I just haven't had time to roll new packages. Please grab a release from GitHub and roll your own package. The manual https://github.com/armijnhemel/binaryanalysis/blob/master/doc/bat-manual.pdf will tell you how.
